from enum import StrEnum
from fastapi import HTTPException, status

class ErrorCode(StrEnum):
    MODEL_NOT_FOUND="MODEL_NOT_FOUND"; MODEL_DOWNLOAD_FAILED="MODEL_DOWNLOAD_FAILED"
    MODEL_CORRUPTED="MODEL_CORRUPTED"; UNSUPPORTED_ARCHITECTURE="UNSUPPORTED_ARCHITECTURE"
    UNSUPPORTED_FORMAT="UNSUPPORTED_FORMAT"; TARGET_UNACHIEVABLE="TARGET_UNACHIEVABLE"
    INSUFFICIENT_MEMORY="INSUFFICIENT_MEMORY"; GPU_OUT_OF_MEMORY="GPU_OUT_OF_MEMORY"
    QUALITY_THRESHOLD_FAILED="QUALITY_THRESHOLD_FAILED"; VALIDATION_FAILED="VALIDATION_FAILED"
    PACKAGING_FAILED="PACKAGING_FAILED"; STORAGE_FAILED="STORAGE_FAILED"; JOB_CANCELLED="JOB_CANCELLED"
    INTERNAL_ERROR="INTERNAL_ERROR"

def api_error(code: ErrorCode, message: str, http_status: int = status.HTTP_422_UNPROCESSABLE_ENTITY, job_id: str | None = None):
    detail = {"error": {"code": code, "message": message}}
    if job_id: detail["error"]["job_id"] = job_id
    raise HTTPException(http_status, detail=detail)
